---
title: "Mini Project 01"
subtitle: "Generalized Linear Models"
output: 
  html_document:
    css: "sta310-project.css"
    highlight: pygments
    fig_height: 4
    fig_width: 6
    toc: true
    toc_depth: 2
    toc_float: true
link-citations: no
bibliography: references.bib
---


For this project you and your team will be (1) evaluating a published article on research that incorporates generalized linear models (GLMs) in the analysis and (2) using data from the article to replicate the analysis for one model. 

The goals of the project are to better understand how GLMs are used in research and to apply what you've learned to analyze real-world data using GLMs. 

## Team assignments

You will work in  teams of 3 - 4 students for this project. [Click here](https://prodduke-my.sharepoint.com/:x:/g/personal/mt324_duke_edu/Edx4me-x0jlEv8ISXQUaKkoBIADRWpu3H5TicViw8i8xfA?e=Zl2U8j) for your team assignment. 

Before getting stared on the proposal:

- Come up with a fun team name. 
- Come up with a plan to communicate and work together outside of lab. 
- Come up with a plan for remote work if some team members are unable to attend lab or other team meetings in person.
- [Click here](https://forms.gle/UJm79abiHtMJ8d356) to submit your new team name.

## Workflow 

- **Project Week 01 (Jan 20)**: Select the article and accompanying data set. Write and submit the proposal.

- **Project Week 02 (week of Mon, Jan 24)**: Read and evaluate the article. Develop an analysis plan.

- **Project Week 03 (week of Mon, Jan 31)**: Work on the analysis. Peer review two teams' initial analysis results. 

- **Project Week 04 (week of Mon, Feb 07)**: Finalize the analysis, presentation, and write up. Present in class on Wed, Feb 09. 


## Due dates

*All work for the project will be submitted on GitHub.*

- **Proposal**: due Fri, Jan 21 at 11:59pm

- **Article evaluation + analysis plan (optional)**: due Fri, Jan 28 at 11:59pm. *Optional submission to receive feedback from the teaching team.*

- **Initial analysis results**: due Tue, Feb 01 at 11:59pm

- **Peer reviews**: due Wed, Feb 03 at 11:59pm

- **Write-up and presentation**: due Wed, Feb 09 at 3:30pm

## Article + data set

The article for this project may be published in an academic journal or in a reputable non-academic publication/website. The article must follow the following criteria: 

- The analysis incorporates the use of one or more GLMs, where at least one is **not** a linear regression model. 
  - *Common GLMs are Poisson regression, Logistic regression, Probit regression, and Negative binomial regression.*
  - *You can also look for models based on the distribution of the response variable: Binary, Binomial, Poisson, Exponential, Gamma, Geometric.*
  
- The original data set analyzed in the article or a comparable data set is available. 

See the [Tips on finding articles](#Tips_on_finding_articles) for tips on searching databases to find articles and data. 

## Proposal 

The proposal should include the following: 

- The citation for the article. *If you're using a `.bib` file you can use the default citation format in R Markdown (Chicago author-date format). Otherwise, use MLA format.*

- Brief summary about why you chose this article.

- Brief summary of the article's primary research objective.

- Name of the GLM(s) used in the article and a short description of the response variable for each model. 

- A `glimpse` of the data set

You are only required to write the proposal for one article and data set. Write the proposal in the file `proposal.Rmd`, then push the .Rmd and knitted PDF to the GitHub repo by the due date for submission.

### Grading criteria 

The proposal will be graded based on the following: 

- All required components of the proposal are included and accurate (6 pts)

- Data set is in the `data` folder of the GitHub repo (2 pts)

- All team members have contributed (2 pts)
  - This will be assessed based on the repo's commit history.
  
## Analysis plan 

The goal of the analysis plan is for you team to outline your approach for the two components of the project analysis. These components are

1. Replicate the modeling process for one GLM in the article. 
2. Conduct original analysis using the data from the article and compare your results to the results from the paper. The comparisons can include an assessment on the conclusions from the model, the performance, addressing violations in model conditions, etc. The original analysis may include 
    - Fitting a model that incorporates new variables and/or data 
    - Fitting a new model (e.g., using different parameter adjustments, transforming the response variable, etc.)
    - Assessing the authors' choice of any adjustments to the model (e.g., adding a penalty term)
    - ...other areas of exploration

### Questions to consider in your analysis plan 

**Below are a few questions to consider as you outline the approach to replicate the modeling process for one GLM in the paper:**

- What data cleaning (if any) is required to prepare the data for modeling? Did the authors remove any observations? Did they create or transform variables? 
- Did the authors conduct model selection? If so, what was their approach?
- Did the authors make any adjustments to the model (e.g., including weighting or a penalty term)? If so, how will you incorporate these adjustments in your model? What questions do you have about these additional model adjustments? 
- Did the authors assess the model fit or performance? If so, how? Otherwise, how will you assess the model fit or performance? 

<br> 

**Below are a few questions to consider as you outline the approach for the original analysis:**

- What question do you want to explore as part of your original analysis? 
- Do you need to add new data and/or create new variables? If so, what do you need to add? - What model will you use? How will you assess model fit and performance? 
- How do your results compare to the results in the article? 

### Submitting the analysis plan (optional)

You may turn in the analysis plan along with any initial results to receive feedback from the teaching team. To do so, 

1. Write your analysis plan to the `proposal.Rmd` document. Knit and push the updated proposal to your team's GitHub repo. 
2. Open a new issue called "Analysis Plan". In the body of the issue add the tag `@sta310-sp22/teaching-team`, so the teaching team is aware the analysis plan is available for review. 



**The analysis plan is optional. If you would like to receive feedback from the teaching team, you must open the issue and submit the analysis plan on GitHub by Friday, January 28 at 11:59pm.** I would suggest your group sketch an analysis plan before diving into the analysis  even if you don't turn it in for feedback. 


## Draft + Peer review

## Final write up

The final write up will include the following: 

- A brief summary of the article and data
- Description of the GLM used in the article
- Description of the process to replicate the model in the article
- Results from replicating the model
- Description of the questions and process for the original analysis
- Discussion of results from the original analysis and how they compared to the original paper
- Discussion on the process of replicating the results from the article

*More details on each section and grading criteria will be added.*


## Presentation 


<!--
Your presentation should generally follow the same structure as your write-up. Each team will have 5 minutes for their presentation, and each team member must speak (roughly equally) during this time. Your presentation will be created using the xaringan package, which allows you to write slides using the same R Markdown structure you’re used to. There is a sample xaringan document in your repo you can edit to your heart’s desire to create your presentation. Roughly I recommend 1 slide for introduction, 2 slides for Question 1, ans 2 slides for Question 2. You can imagine spending roughly one minute on each slide. You should feel free to have more (or fewer) slides. Your evaluation will be based on your content, professionalism (including sticking to time), and your performance during the Q&A (question and answer). We don’t care how many slides you use to do this.
-->

## GitHub repo organization 

You should have the following files and folders in the project repo: 

- `/data/`: The data set
  - `/data/*`: File containing data set 
  - `/data/README.md`: Codebook for data set. 
  
- `README.md`: 3 - 5 sentence summary of the project 

- `/proposal`: Folder for project proposal 
  - `/proposal/proposal.Rmd`: R Markdown file for proposal 
  - `/proposal/proposal.pdf`: Knitted PDF of proposal 
  
- `/writeup/`: Folder for write up 
  - `/writeup/writeup.Rmd`: R Markdown file for write up
  - `/writeup/writeup.pdf`: Knitted PDF of write up
  
- `/presentation`: Folder for presentation 
  - `/presentation/*`: Presentation file (if not linked in README)
  - `/presentation/README.md`: Link to project (if not in presentation folder)

## Grading (100 points)

| Component           | Points  |
|---------------------|---------|
| Proposal            | 10 pts  |
| Peer review         | 15 pts  |
| Written report      | 35 pts  |
| Presentation        | 25 pts  |
| Organization        | 5 pts   |
| Teamwork evaluation | 10 pts  |

## Tips on finding articles

Below are tips to help you find articles based on information from [Jodi Psoter](https://directory.library.duke.edu/staff/jodi.psoter), the Librarian for Chemistry and Statistical Science at Duke Libraries.

### PubMed

*Articles in health-related fields*

The [PubMed heading tree](https://www.ncbi.nlm.nih.gov/mesh/68013223) lets you search by topic. The link will direct you to the results under the category of "Statistics as a Topic".

  1. Click on the model / analysis of interest.
   2. Click "Add to search builder" under the *PubMed Search Builder* in the top right corner. You should now see the model/analysis type you chose in the search box. 
  3. Click "Search PubMed", and a page of search results will appear. 
  4. There are options to narrow your results on the left-hand side. Under *Article Attributes*, check "Associated Data", to limit the results to articles with data sets available.

You can use the other search options to narrow down results based on your team's interests. 

### PsycInfo

*Articles in psychology*

[PsycInfo](https://web-s-ebscohost-com.proxy.lib.duke.edu/ehost/search/advanced?vid=0&sid=b34cb1a4-7ba3-4cf4-8ec2-1da4f69a87a3%40redis) will allow users to search by analysis type. 

1. Put the name of the model in the search bar, e.g., "Poisson Regression". Then, in the drop down menu next to the search bar, select "DE Subjects [exact]". Click Search.

2. On the left-hand side, under *Limit To*, check "Open Access". This will not guarantee the article has an associated data set, but a lot of open access articles will make the data available or utilize publicly accessible data you could pull from another source. 

### Web of Science 

*Articles on all topics*

[Web of Science Data Citation Index](https://www-webofscience-com.proxy.lib.duke.edu/wos/drci/basic-search) lets you search for data sets based on the topic of interest. 

1. Use the search bar to search based on a topic of interest. You can also search for the model / analysis type. 

2. On the left-hand side, check "Data Set" under *Content Type* and check "Dataset" under *Data Types*. Click "Refine" to limit the results. 

3.Click on the article of interest. 

4. Click the *DOI* link in the article metadata. The article should have a data availability statement or something similar with information on accessing the data.


