---
title: "Models and output for Quiz 04"
format:
  html:
    self-contained: true
    toc: true
    html-math-method: katex
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
```

## Model B and C

Output from Models B and C in [Chapter 10 of Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-3level.html). 

The response variable $Y_{ijk}$ is the is the height (in mm) of plant $j$ from pot $i$ at time $k$. See [Case Studies: Germination](https://bookdown.org/roback/bookdown-BeyondMLR/ch-3level.html#cs:seeds) for a full description of the data and research question. 


### Model B

From [Section 10.4.2](https://bookdown.org/roback/bookdown-BeyondMLR/ch-3level.html#unconditional-growth). 

$$Y_{ijk}=[\alpha_{0}+\beta_{0}\textrm{time}_{ijk}]+
[\tilde{u}_{i}+{v}_{ij}+\epsilon_{ijk}+(\tilde{v}_{i}+{v}_{ij})\textrm{time}_{ijk}]$$

where $\epsilon_{ijk}\sim N(0,\sigma^2)$,

$$\left[ \begin{array}{c}
            u_{ij} \\ v_{ij}
          \end{array}  \right] \sim N \left( \left[
          \begin{array}{c}
            0 \\ 0
          \end{array} \right], \left[
          \begin{array}{cc}
            \sigma_{u}^{2} & \\
            \sigma_{uv} & \sigma_{v}^{2}
          \end{array} \right] \right), and$$
          
$$\left[ \begin{array}{c}
            \tilde{u}_{i} \\ \tilde{v}_{i}
          \end{array}  \right] \sim N \left( \left[
          \begin{array}{c}
            0 \\ 0
          \end{array} \right], \left[
          \begin{array}{cc}
            \sigma_{\tilde{u}}^{2} & \\
            \sigma_{\tilde{u}\tilde{v}} & \sigma_{\tilde{v}}^{2}
          \end{array} \right] \right).$$

### Model C

[From Section 10.5](https://bookdown.org/roback/bookdown-BeyondMLR/ch-3level.html#sec:boundary)

$$\begin{align*}
Y_{ijk} & = [\alpha_{0}+\alpha_{1}\textrm{strl}_{i}+\alpha_{2}\textrm{cult}_{i}+\alpha_{3}\textrm{rem}_{i} +
 \beta_{0}\textrm{time}_{ijk} + \\
 & \beta_{1}\textrm{strl}_{i}\textrm{time}_{ijk}+\beta_{2}\textrm{cult}_{i}\textrm{time}_{ijk}+ \beta_{3}\textrm{rem}_{i}\textrm{time}_{ijk}] + \\
 & [\tilde{u}_{i}+u_{ij}+\epsilon_{ijk}+\tilde{v}_{i}\textrm{time}_{ijk}+v_{ij}\textrm{time}_{ijk}]
\end{align*}$$

where $\epsilon_{ijk}\sim N(0,\sigma^2)$,

$$\left[ \begin{array}{c}
            u_{ij} \\ v_{ij}
          \end{array}  \right] \sim N \left( \left[
          \begin{array}{c}
            0 \\ 0
          \end{array} \right], \left[
          \begin{array}{cc}
            \sigma_{u}^{2} & \\
            \sigma_{uv} & \sigma_{v}^{2}
          \end{array} \right] \right), and$$
          
$$\left[ \begin{array}{c}
            \tilde{u}_{i} \\ \tilde{v}_{i}
          \end{array}  \right] \sim N \left( \left[
          \begin{array}{c}
            0 \\ 0
          \end{array} \right], \left[
          \begin{array}{cc}
            \sigma_{\tilde{u}}^{2} & \\
            \sigma_{\tilde{u}\tilde{v}} & \sigma_{\tilde{v}}^{2}
          \end{array} \right] \right).$$

## Table 10.4 from BMLR 

```{r, include=FALSE}
Variable <- c("Intercept", "Female", "Married", "Separated or divorced", "Single", "Homeowner", "Latino", "Black", "Mobility", "Age", "Years in neighborhood", "SES", "Concentrated disadvantage", "Immigrant concentration", "Residential stability", "Within neighborhoods", "Between neighborhoods", "Within neighborhoods", "Between neighborhoods")
Coefficient <- c(3.523, -0.012, -0.005, -0.045, -0.026, 0.122, 0.042, -0.029, -0.025, 0.0021, 0.0006, 0.035, -0.172, -0.037, 0.074, 0.320, 0.026, 3.2, 70.3)
SE2 <- c("0.013", "0.015", "0.021", "0.026", "0.024", "0.020", "0.028", "0.030", "0.007", "0.0006", "0.0008", "0.008", "0.016", "0.014", "0.013", " ", " ", " ", " ")
tratio <- c("263.20", "-0.76", "-0.25", "-1.72", "-1.05", "6.04", "1.52", "-0.98", "-3.71", "3.47", "0.78", "4.64", "-10.74", "-2.66", "5.61", " ", " ", " ", " ")
```

```{r, table4chp10, echo=FALSE}
table4chp10 <- data.frame(Variable, Coefficient, SE2, tratio)
colnames(table4chp10) <- c("Variable", "Coefficient", "SE",
                           "t ratio")
table4chp10[6,2] <- paste0(table4chp10[6,2])
table4chp10[10,2] <- paste0(table4chp10[10,2])
table4chp10[12,2] <- paste0(table4chp10[12,2])
table4chp10[14,2] <- paste0(table4chp10[14,2])
table4chp10[15,2] <- paste0(table4chp10[15,2])
kable(table4chp10, booktabs=T, escape=F,
      caption="Correlates of collective efficacy from Table 3 of Sampson et al. (1997).") %>%
  kable_styling(latex_options = "scale_down") %>%
  pack_rows("Person-level predictors", 2, 12) %>%
  pack_rows("Neighborhood-level predictors", 13, 15) %>%
  pack_rows("Variance components", 16, 17) %>%
  pack_rows("Percent of variance explained", 18, 19)
```