---
title: "Homework 01"
subtitle: "due Wednesday, January 19 at 11:59pm EST"
output: 
  tufte::tufte_html:
    css: "sta310-hw.css"
    tufte_variant: "envisioned"
    highlight: pygments
    fig_height: 4
    fig_width: 6
    toc: true
    toc_depth: 1
link-citations: no
bibliography: references.bib
---

# Learning goals 

This assignment is a review of multiple linear regression. The goal is that by the end of the assignment, you are able to 

- produce and interpret plots and summary statistics.
- fit and interpret the coefficients of a linear model.
- use statistical inference to draw conclusions about predictor variables.
- understand assumptions for linear regression and identify potential violations.
- use statistical measures to select model of best fit. 
- complete assignment using a reproducible workflow that includes writing results in R Markdown and using GitHub for version control.

# Instructions

[FILL IN INSTRUCTIONS!]

# Exercises 

*Note: All exercises are adapted from exercises in Chapter 1 of Beyond Multiple Linear Regression.*

## Conceptual 

1. Researchers record the number of cricket chirps per minute and temperature during that time to investigate whether the number of chirps varies with the temperature.[^ex1]
  
    **a.** Identify the response and explanatory variable(s).
    
    **b.** Write the assumptions for linear regression in the context of the problem. 

2. For each of over 27,000 overnight permits for the Boundary Waters Canoe area, the zip code for the group leader has been translated to the distance traveled and socioeconomic data. Thus, for each zip code we can model the number of trips made as a function of distance traveled and various socioeconomic measures. ^[from Sec. 1.8.1, Ex 2]

    **a.** Identify the response and explanatory variable(s). 
    
    **b.** Identify which model assumption(s) are violated. Briefly explain your choice.

3. In a 2011 article in *The Sport Journal*, @farrar2011new attempt to show that Major League Baseball general managers did not immediately embrace the findings of Michael Lewis’s 2003 *Moneyball* book (Lewis 2003)^[Full citation]. They contend that players’ on-base percentage remained relatively undercompensated compared to slugging percentage three years after the book came out. Two regression models are described: Team Run Production Model and Player Salary Model.^[from Sec. 1.8.1, Ex 4]

    [Click here](articles/thesportjournal.org-A New Test of the Moneyball Hypothesis.pdf) for a PDF of the article.

 <!--   **a.** Discuss potential concerns (if any) with the assumptions for linear regression in each model. -->
    
    **b.** In Table 3: Coefficients for the Team Run Production Model (pg. 9), the authors contend that Model 1 is better than Model 3.
    Could you argue that Model 3 is actually better? Briefly epxlain. 
    
    **c.** Explain how you could run a formal hypothesis test comparing Model 1 to Model 3 to determine which is better.
    
    **d.** In Table 4 (pg. 10), Model 1 has a higher $Adj. R^2$ than Model 2, yet the extra term in Model 1 (an indicator value for the National League) is not significant at the 5% level. Explain how this is possible.

## Guided Exercises 

4. In the 1970’s, Harris Trust was sued for gender discrimination in the salaries it paid its employees. One approach to addressing this issue was to examine the starting salaries of all skilled, entry-level clerical workers between 1965 and 1975. The following variables, which can be found in banksalary.csv, were collected for each worker [@ramsey2012statistical].^[Sec. 1.8.2, Ex 1]

    - `bsal` = beginning salary (annual salary at time of hire)
    - `sal77` = annual salary in 1977
    - `sex` = MALE or FEMALE
    - `senior` = months since hired
    - `age` = age in months
    - `educ` = years of education
    - `exper` = months of prior work experience

    *Note: Creating an indicator variable based on sex could be helpful.*

<!--    **a.** The mean starting salary of male workers ($5957) was 16% higher than the mean starting salary of female workers ($5139). Confirm these mean salaries. Is this enough evidence to conclude gender discrimination exists? If not, what further evidence would you need? -->
    
    **b.** How would you expect age, experience, and education to be related to starting salary? Generate appropriate exploratory plots; are the relationships as you expected?
    
    **c.** Why might it be important to control for seniority (number of years with the bank) if we are only concerned with the salary when the worker started?
    
    **d.** By referring to exploratory plots and summary statistics, are any explanatory variables (including sex) closely related to each other? What implications does this have for modeling?
    
    **e.** A potential final model would contain terms for seniority, education, and experience in addition to sex. State a 95% confidence interval for sex and interpret this interval carefully in the context of the problem.

    **g.** Based on your final model, do you find evidence of gender discrimination at Harris Trust? Briefly explain.
-->

5. Housing prices and log transformations. The dataset kingCountyHouses.csv contains data on over 20,000 houses sold in King County, Washington (@kingcounty).^[Sec. 1.8.2, Ex 3]

    We will use the following variables:
    - `price` = selling price of the house
date = date house was sold, measured in days since January 1, 2014
    - `sqft` = interior square footage

    *See textbook for full list of variables.*
    
    **a.** Fit a simple linear regression model with price as the response variable and sqft as the explanatory variable (Model 1). Interpret the slope coefficient. 
    
    **b.** Create a new variable, `logprice`, the natural log of price. Fit Model 2, where `logprice` is now the response variable and `sqft` is still the explanatory variable. Write out the regression equation.  How does `logprice` change when `sqft` increases by 1?
    
    **c.** Recall that $$\log(\frac{a}{b}) = \log(a) - \log(b)$$ Use this to to derive how price changes as sqft increases by 1. Write your response using appropriate mathematical notation.
    
    **d.** Fit Model 3 where price and logsqft are the response and explanatory variables, respectively. Write out the regression line equation.
    
    **e.** Based on Model 3, how does predicted price change as sqft increases by 1%? *As a hint, this is the same as multiplying sqft by 1.01.*

<!--    
    **f.** Fit Model 4, with `logsqft` and `logprice` as the response and explanatory variables, respectively. Write out the regression line equation.
    
    **g.** In Model 4, what is the effect on price corresponding to a 1% increase in sqft?
-->

# Submission

**Before you wrap up the assignment, make sure all documents are updated on your GitHub repo. We will be checking these to make sure you have been practicing how to commit and push changes.**

**Remember -- you must turn in a PDF file to the Gradescope page before the submission deadline for full credit.** 

To submit your assignment: 

- Go to http://www.gradescope.com and click *Log in* in the top right corner. 

- Click *School Credentials* `r emo::ji("arrow_right")` *Duke NetID* and log in using your NetID credentials.

- Click on your *STA 310* course. 

- Click on the assignment, and you'll be prompted to submit it.

- Mark the pages associated with each exercise. All of the pages of your assignment should be associated with at least one question (i.e., should be "checked"). 

- Select the first page of your .PDF submission to be associated with the *"Workflow & formatting"* section.



# Grading

| **Total** | **50** |
|-------------------------------------------------------------|:--:|
| Ex 1 | 3 |
| Ex 2 | 3 |
| Ex 3 | 9|
| Ex 4 | 17 | 
| Ex 5 | 15 |
| Workflow & formatting | 3|

-  The "Workflow & formatting" grade is to based on the organization of the assignment write up along with the reproducible workflow. This includes ans having an organized write up with neat and readable headers, code, ad narrative, including properly rendered mathematical notation. It also includes having a reproducible R Markdown document used to render the submitted PDF, and implementing version using multiple commits with informative commit messages.

## References
